import { ParsedCSVData } from '@/types'
import jsPDF from 'jspdf'
import html2canvas from 'html2canvas'

export interface ExportData {
  checkingData?: ParsedCSVData | null
  creditData?: ParsedCSVData | null
  companyName?: string
  reportDate?: string
}

/**
 * Export financial data to CSV format
 */
export function exportToCSV(data: ExportData): void {
  const { checkingData, creditData } = data
  
  if (!checkingData && !creditData) {
    alert('No data available to export')
    return
  }

  let csvContent = ''
  
  // Add checking account data
  if (checkingData) {
    csvContent += 'CHECKING ACCOUNT DATA\n'
    csvContent += 'Date,Description,Amount,Type,Category,Balance\n'
    
    checkingData.transactions.forEach(transaction => {
      csvContent += `"${transaction.date}","${transaction.description}","${transaction.amount}","${transaction.type}","${transaction.category || ''}","${transaction.balance || ''}"\n`
    })
    
    csvContent += '\n'
  }
  
  // Add credit card data
  if (creditData) {
    csvContent += 'CREDIT CARD DATA\n'
    csvContent += 'Date,Description,Amount,Type,Category\n'
    
    creditData.transactions.forEach(transaction => {
      csvContent += `"${transaction.date}","${transaction.description}","${transaction.amount}","${transaction.type}","${transaction.category || ''}"\n`
    })
    
    csvContent += '\n'
  }
  
  // Add summary data
  csvContent += 'FINANCIAL SUMMARY\n'
  csvContent += 'Account,Total Credits,Total Debits,Net Amount,Transaction Count\n'
  
  if (checkingData) {
    csvContent += `"Checking Account","${checkingData.summary.totalCredits}","${checkingData.summary.totalDebits}","${checkingData.summary.netAmount}","${checkingData.summary.totalTransactions}"\n`
  }
  
  if (creditData) {
    csvContent += `"Credit Card","${creditData.summary.totalCredits}","${creditData.summary.totalDebits}","${creditData.summary.netAmount}","${creditData.summary.totalTransactions}"\n`
  }
  
  // Download CSV
  downloadFile(csvContent, 'financial-report.csv', 'text/csv')
}

/**
 * Export financial data to PDF format
 */
export function exportToPDF(data: ExportData): void {
  const { checkingData, creditData, companyName = 'Markman Group', reportDate = new Date().toLocaleDateString() } = data
  
  if (!checkingData && !creditData) {
    alert('No data available to export')
    return
  }

  const doc = new jsPDF()
  const pageWidth = doc.internal.pageSize.getWidth()
  const pageHeight = doc.internal.pageSize.getHeight()
  let yPosition = 20

  // Header
  doc.setFontSize(20)
  doc.setFont('helvetica', 'bold')
  doc.text(`${companyName} Financial Report`, pageWidth / 2, yPosition, { align: 'center' })
  
  yPosition += 10
  doc.setFontSize(12)
  doc.setFont('helvetica', 'normal')
  doc.text(`Generated on: ${reportDate}`, pageWidth / 2, yPosition, { align: 'center' })
  
  yPosition += 20

  // Account Summaries
  if (checkingData) {
    addAccountSummary(doc, 'Checking Account', checkingData.summary, yPosition)
    yPosition += 60
  }
  
  if (creditData) {
    addAccountSummary(doc, 'Credit Card', creditData.summary, yPosition)
    yPosition += 60
  }

  // Category Breakdown
  if (checkingData && checkingData.categories.length > 0) {
    yPosition = addCategoryBreakdown(doc, 'Spending Categories', checkingData.categories, yPosition)
  }

  // Monthly Data
  if (checkingData && checkingData.monthlyData.length > 0) {
    yPosition = addMonthlyData(doc, 'Monthly Cash Flow', checkingData.monthlyData, yPosition)
  }

  // Footer
  doc.setFontSize(10)
  doc.setFont('helvetica', 'italic')
  doc.text('This report was generated by Markman Group Financial Dashboard', pageWidth / 2, pageHeight - 10, { align: 'center' })

  // Download PDF
  doc.save(`financial-report-${new Date().toISOString().split('T')[0]}.pdf`)
}

/**
 * Export dashboard as image (PNG)
 */
export async function exportDashboardAsImage(elementId: string, filename: string = 'dashboard-screenshot.png'): Promise<void> {
  const element = document.getElementById(elementId)
  if (!element) {
    alert('Dashboard element not found')
    return
  }

  try {
    const canvas = await html2canvas(element, {
      scale: 2,
      useCORS: true,
      allowTaint: true,
      backgroundColor: '#ffffff'
    })
    
    const link = document.createElement('a')
    link.download = filename
    link.href = canvas.toDataURL('image/png')
    link.click()
  } catch (error) {
    console.error('Error generating image:', error)
    alert('Error generating dashboard image')
  }
}

// Helper functions
function addAccountSummary(doc: jsPDF, accountName: string, summary: any, yPosition: number): void {
  doc.setFontSize(14)
  doc.setFont('helvetica', 'bold')
  doc.text(accountName, 20, yPosition)
  
  yPosition += 10
  doc.setFontSize(10)
  doc.setFont('helvetica', 'normal')
  
  const details = [
    `Total Credits: $${summary.totalCredits.toLocaleString()}`,
    `Total Debits: $${summary.totalDebits.toLocaleString()}`,
    `Net Amount: $${summary.netAmount.toLocaleString()}`,
    `Transactions: ${summary.totalTransactions}`,
    `Date Range: ${summary.dateRange.start} to ${summary.dateRange.end}`
  ]
  
  details.forEach(detail => {
    doc.text(detail, 20, yPosition)
    yPosition += 6
  })
}

function addCategoryBreakdown(doc: jsPDF, title: string, categories: any[], yPosition: number): number {
  doc.setFontSize(14)
  doc.setFont('helvetica', 'bold')
  doc.text(title, 20, yPosition)
  
  yPosition += 10
  doc.setFontSize(10)
  doc.setFont('helvetica', 'normal')
  
  categories.slice(0, 10).forEach(category => {
    const text = `${category.category}: $${category.amount.toLocaleString()} (${category.percentage.toFixed(1)}%)`
    doc.text(text, 20, yPosition)
    yPosition += 6
  })
  
  return yPosition + 10
}

function addMonthlyData(doc: jsPDF, title: string, monthlyData: any[], yPosition: number): number {
  doc.setFontSize(14)
  doc.setFont('helvetica', 'bold')
  doc.text(title, 20, yPosition)
  
  yPosition += 10
  doc.setFontSize(10)
  doc.setFont('helvetica', 'normal')
  
  monthlyData.slice(-6).forEach(month => {
    const monthName = new Date(month.month + '-01').toLocaleDateString('en-US', { month: 'short', year: '2-digit' })
    const text = `${monthName}: $${month.netFlow.toLocaleString()} (${month.transactionCount} transactions)`
    doc.text(text, 20, yPosition)
    yPosition += 6
  })
  
  return yPosition + 10
}

function downloadFile(content: string, filename: string, mimeType: string): void {
  const blob = new Blob([content], { type: mimeType })
  const url = URL.createObjectURL(blob)
  const link = document.createElement('a')
  link.href = url
  link.download = filename
  document.body.appendChild(link)
  link.click()
  document.body.removeChild(link)
  URL.revokeObjectURL(url)
}